CREATE TABLE IF NOT EXISTS proxy_config_versions (version BIGINT PRIMARY KEY, payload TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS proxy_events (id BIGSERIAL PRIMARY KEY, kind TEXT NOT NULL, detail TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
